package training.java6.ocp.generics;

/**
 * @see https://docs.oracle.com/javase/tutorial/java/generics/bridgeMethods.html
 */
public class TypeEnsureTraining {

	public static class Node<T> {

		public T data;

		public Node(T data) {
			this.data = data;
		}
		
		/**
		 * Bridge method generated by the compiler
		 */
		/*
	    public void setData(Object data) {
	        setData((Integer) data);
	    }*/

		public void setData(T data) {
			System.out.println("Node.setData");
			this.data = data;
		}
	}

	public static class MyNode extends Node<Integer> {

		public MyNode(Integer data) {
			super(data);
		}
		
		/**
		 * Bridge method generated by the compiler
		 */
		/*
	    public void setData(Object data) {
	        setData((Integer) data);
	    }*/
		
		public void setData(Integer data) {
			System.out.println("MyNode.setData");
			super.setData(data);
		}
	}

	public static void main(String[] args) {
		MyNode mn = new MyNode(5);
		Node n = (MyNode) mn;
		n.setData("Hello");//Causes a ClassCastException to be thrown.
		Integer x = mn.data;
	}

}
